version: "2"
containers:
- name: vscode
  image: caretdev/code-server
  cmd: --auth none --disable-telemetry --port=8080
  shell: sudo -u coder -s /bin/bash
  ports:
  - 8080
  memory: 1024
- name: iris
  image: store/intersystems/iris-community:2020.4.0.524.0
  shell: su - irisowner -c 'iris session iris'
  ports:
  - 52773
  - 1972
  memory: 1024
