#!/bin/bash

count=$(find /opt/intersystems/src/services/samples -name '*.json' | wc -l)
if [ $count -ne 5 ]; then
  fail-message "Did you call createproducts.sh?"
fi

list=$(curl http://iris:52773/api/coffeeco/catalog/getproducts/1 | jq '.products[].product_code' --raw-output && \
 curl http://iris:52773/api/coffeeco/catalog/getproducts/0 | jq '.products[].product_code' --raw-output)
list=${list[@]}
list=${list// /,}

if [[ $list != "BRAZILDARK,ETHIOPIAMEDIUM,GUATEMALALIGHT,SUMATRADARK,SUMATRALIGHT" ]]; then
  fail-message "Did you call loadproducts.sh?"
fi
